version: "3.9"
services:
  api:
    build:
      context: backend
      dockerfile: Dockerfile
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - "8080:8080"
    
  app:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    stdin_open: true
